###########################################################################################################
#                                            PARAMETERS
###########################################################################################################

# Directories
JAR_DIR = '../../resources/jar/'
SRC_DIR = '../../src/'
OUTPUT_DIR = '../../resources/sample_run/'

# Inputs
FASTQ = '../../resources/sample_data/sampleReads.fq'
MIRNA_FASTA = '../../resources/sample_data/miRBase21_mature_mmu.fa'
MIRNA_TO_GROUP = '../../resources/sample_data/families_miRBase21_mature_mmu.txt'

# Misc parameters
KMER_SIZE = '20'
COUNT_PLUS_STRAND_MAPPINGS_ONLY = True


###########################################################################################################
#                                             FUNCTIONS
###########################################################################################################

def boolean_to_java_str(bool):
	if bool:
		return 'true'
	else:
		return 'false'


###########################################################################################################
#                                             VARIABLES
###########################################################################################################

# Programs
KMER_SEARCH = JAR_DIR + '/PerfectKmerSearch.jar'
COUNT_ALIGNMENTS = JAR_DIR + '/AlignmentCountsByReference.jar'
COMBINE_COUNTS = JAR_DIR + '/CombineCountsByGroup.jar'

# Output files
UNSORTED_BAM = OUTPUT_DIR + '/kmer.bam'
COORD_SORTED_BAM = OUTPUT_DIR + '/kmer.sorted.bam'
COORD_SORTED_BAI = OUTPUT_DIR + '/kmer.sorted.bai'
FINAL_COUNTS = OUTPUT_DIR + '/final_counts.txt'

# Misc variables
PLUS_STRAND_ONLY_JAVA = boolean_to_java_str(COUNT_PLUS_STRAND_MAPPINGS_ONLY)


###########################################################################################################
#                                              RULES
###########################################################################################################

rule all:
	input:
		FINAL_COUNTS


rule kmer_match_to_reference:
	input:
        	MIRNA_FASTA
	output:
        	UNSORTED_BAM
	shell:
		'java -jar {KMER_SEARCH} -b {output} -fa {input} -fq {FASTQ} -k {KMER_SIZE}'


rule sort_bam:
	input:
		UNSORTED_BAM
	output:
		COORD_SORTED_BAM
	shell:
		'samtools sort -o {output} -T {output}.tmp {input}'
		

rule index_bam:
	input:
		COORD_SORTED_BAM
	output:
		COORD_SORTED_BAI
	shell:
		'samtools index {input} {output}'
		

rule collapse_counts_by_families:
	input:
		COORD_SORTED_BAM,
		COORD_SORTED_BAI,		
		MIRNA_TO_GROUP
	output:
		FINAL_COUNTS
	shell:
		'java -jar {COMBINE_COUNTS} -b {COORD_SORTED_BAM} -f {MIRNA_FASTA} -g {MIRNA_TO_GROUP} -p {PLUS_STRAND_ONLY_JAVA} -o {output}'



