#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: makeFamiliesMiRBase <fasta file of miRNAs>"
    exit -1
fi

cat $1 | grep ">" | perl -pi -e 's/>//g' > tmp_nm

cat tmp_nm | \
perl -pi -e 's/miR\-9\-/miR\-09\-/g' | \
perl -pi -e 's/\-[0-9]\-/\-/g' | \
perl -pi -e 's/\.2-3p//g' | \
perl -pi -e 's/\.2-5p//g' | \
paste tmp_nm -

rm tmp_nm

